config/routes.rb
ZIBAStyle::Application.routes.draw do

  mount Mercury::Engine => '/'

  resources :home_page_entities
  resources :home_page, only: :index do 
    collection {
      get :admin
      post :admin
    }
  end

  WepayRails.routes(self)
  
  resources :categories
  match 'categories/:id/:category_id' => 'categories#show'
  
  resources :contacts, only: [:index, :create, :show] do
    collection { get :contact_us, :request_invitation }
  end
  resources :credits
  resources :designers, only: [:index, :show, :edit, :update ] do
    collection { get :activate, :boutique, :sales_report, :force_apply, :videos, :settings, :upload_designers_page_banner
                 put  :deactivate_boutique_request, :upload_designers_page_banner
                 post :sales_report }
    member { get :detailed_view } 
  end

  match '/designers/:id/upload_banner' => 'designers#upload_banner', as: 'upload_banner'

  resources :designer_orders, only: [:index, :show, :edit, :update ]
  resources :designer_videos
  resources :countries do
    member { post :mercury_update
             get :history }
  end

  resources :editor_picks
  
  match '/shopping_bag'     => 'cart#index',  via: :get,  as: 'shopping_bag'
  match '/shopping_bag'     => 'cart#create', via: :post, as: 'shopping_bag'
  match '/shopping_bag/:id' => 'cart#update', via: :put,  as: 'shopping_bag'
  
  resources :cart, only: [:index, :create, :update ]
  
  resources :feedbacks, only: [:index, :new, :create ]
  resources :file_attachments, only: [:update, :show]

  match '/file_attachments/:id/crop_studio/:style', to: 'file_attachments#crop_studio', as: :crop_style

  resources :invitations, only: [:index, :create ]
  resources :orders, except: [:create, :new, :destroy ]
  resources :pages do
    member { post :mercury_update }
  end

  match '/export_products' => 'products#export_products'
  match '/export_users' => 'users#export_users'
  resources :products do
    member { get :share, :share_by_email, :crop_studio, :size_chart }
  end
  resources :returns, except: :delete do 
    member { put :restock }
  end
  
  resources :sales, only: [:index, :edit, :update]

  match '/browsing_gender/:gender' => 'users#browsing_gender', as: 'browsing_gender', via: :put

  resources :search, only: [:index, :create]

  match 'products/:id/sizes'    => 'products#sizes', as: :products_sizes
  match 'products/:id/shipping' => 'products#edit', action_type: "shipping", as: :products_shipping

  match '/checkout'           => 'orders#checkout',           via: [:get,:post]
  match '/checkout'           => 'orders#update',             via: [:put]
  match '/validate_checkout'  => 'orders#validate_checkout'
  match '/cancel_checkout'    => 'orders#cancel_checkout',    via: :post
  match '/order_complete'     => 'orders#order_complete',     via: :get
  match '/review_orders'      => 'feedbacks#customer_index',  via: :get

  match '/designers_feedbacks' => 'feedbacks#index', user_type: "designer", via: :get
  match '/designer_returns'    => 'returns#designer_returns', via: :get
  match '/style_directory'     => 'designers#style_directory', via: :get
  match '/become_designer'     => 'designers#become_designer', via: :get, as: :become_designer
  match '/become_designer'     => 'designers#switch_to_designer', via: :post, as: :become_designer
  match '/designer_accepted/:authentication_token' => 'designers#accepted', via: :get, as: :designer_accepted

  match '/about'                => 'pages#show',                id: "about",                via: :get
  match '/style_directory'      => 'pages#show',                id: "style",                via: :get
  match '/privacy'              => 'pages#show',                id: "privacy",              via: :get
  match '/terms_of_service'     => 'pages#show',                id: "terms_of_service",     via: :get
  match '/membership'           => 'pages#show',                id: "membership",           via: :get
  match '/faq'                  => 'pages#show',                id: "faq",                  via: :get
  match '/shipping_and_returns' => 'pages#show',                id: "shipping_and_returns", via: :get
  match '/blog'                 => 'pages#blog',                id: "blog",                 via: :get
 
  match '/about'                => 'pages#update',                id: "about",                via: :put
  match '/style_directory'      => 'pages#update',                id: "style",                via: :put
  match '/privacy'              => 'pages#update',                id: "privacy",              via: :put
  match '/terms_of_service'     => 'pages#update',                id: "terms_of_service",     via: :put
  match '/membership'           => 'pages#update',                id: "membership",           via: :put
  match '/faq'                  => 'pages#update',                id: "faq",                  via: :put
  match '/shipping_and_returns' => 'pages#update',                id: "shipping_and_returns", via: :put
  
  match '/contact_us'       => 'contacts#contact_us',                                 via: :get
  match '/engage_with_us'   => 'contacts#engage_with_us',                             via: :get
 
 
  match 'admin/approve_designers'   => 'admin#approve', action_name: "approve_designers",   via: [:get, :post]
  match 'admin/authorize_designers' => 'admin#approve', action_name: "authorize_designers", via: [:get, :post]
  match 'admin/approve_products'    => 'admin#approve', action_name: "approve_products",    via: [:get, :post]
  match 'admin/approve_videos'      => 'admin#approve', action_name: "approve_videos",      via: [:get, :post]
  match 'admin/orders'              => 'orders#index',  user_type: "admin",                 via: :get
  match 'admin/returns'             => 'returns#index', user_type: "admin",                 via: :get
  match 'admin/returns/:id/edit'    => 'returns#edit',  user_type: "admin",                 via: :get, as: :admin_edit_return
  match 'admin/products'            => 'products#index',user_type: "admin",                 via: :get
  match 'admin/countries'           => 'countries#admin_index',                             via: :get, as: :admin_countries
  match 'admin/switch_to_designer'  => 'admin#switch_to_designer',                          via: :post
  match 'admin/switch_to_admin'     => 'admin#switch_to_admin',                             via: :post

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords"  } 
  devise_scope :user do
    root to: 'home_page#index'
    match 'designer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :designer ], via: :get
    match 'designer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :designer ], via: :post
    match 'customer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :customer ], via: :get
    match 'customer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :customer ], via: :post
    match '/invite/:invitation_token' => 'users/registrations#new',    role: User::ROLE[ :customer ], as: "customer_sign_up_with_invitation"
    match '/account'                  => 'users/registrations#edit',   view: "account", via: :get
    match '/shipping_info'            => 'users/registrations#edit',   view: "shipping", via: :get
    match '/designer_accepted_registration/:authentication_token' => 'users/registrations#edit', via: :get, as: :designer_accepted_registration

  end
 
  resources :users, only: [:index, :edit, :update]

  match '*not_found', to: 'errors#error_404'
  

end

app/views/notifier/send_admin_new_boutique_designer_to_approve_notification.html.slim
table style="border-collapse:collapse;"
  tr
    td width="25"
    td width="600" style="font-size: 14px;font-weight: 100;line-height: 20px;text-align:center;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;"
      p #{link_to "#{@designer.fname} #{@designer.lname}", designer_url(@designer)} has submitted a boutique for approval.
      br
      p #{link_to "View boutique for approval", admin_approve_designers_url}
      br
    td width="25"
  tr  
    td width="650" height="10" colspan="3"

app/views/notifier/send_admin_new_designer_signup_notification.html.slim
table style="display:inline-block;border-collapse:collapse;"
  tr
    td width="25"
    td width="600" style="font-size: 14px;font-weight: 100;line-height: 20px;text-align:center;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;"
      p #{link_to "#{@designer.fname} #{@designer.lname}", designer_url(@designer)} has applied to be featured on ZIBA Style.
      br
      p #{link_to "Review the application here", admin_authorize_designers_url}
      br
    td width="25"
  tr
    td width="650" height="10" colspan="3"

app/views/notifier/send_admin_new_product_designer_to_approve_notification.html.slim
table style="display:block;border-collapse:collapse;"
  tr
    td width="25"
    td width="600" style="font-size: 14px;font-weight: 100;line-height: 20px;text-align:center;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;"
      p #{link_to "#{@designer.fname} #{@designer.lname}", designer_url(@designer)} has submitted a product for approval.
      br
      p #{link_to "View product for approval", product_url(@product)}
      br
    td width="25"
  tr
    td width="25"
    td width="600" height="10"
    td width="25"

app/views/notifier/send_customer_welcome_notification.html.slim
doctype transitional
html
  head
    <meta content="text/html; charset=UTF-8; format='flowed'" http-equiv="Content-Type" />
    <style type="text/css">.ReadMsgBody {width: 100%;} .ExternalClass {width: 100%;}</style>
    title ZIBA Style
  body
    div style="text-align:center;display:inline;"
      p style="color:#a6a6a6;margin:10px;" To ensure delivery to your inbox, please add <a href="mailto:support@ziba-style.com">support@ziba-style.com</a> to your address book.
      div style="margin-left:auto;margin-right:auto;width:100%;text-align:left;"
        table align="center" style="border-collapse:collapse;border-left:solid 1px black;border-right:solid 1px black;margin:auto;" width="650"
          tr
            td style="padding:0;"
              table style="border-collapse:collapse;"
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
                    a
                tr
                  td width="25" height="33" style="background-color:black;"
                    a
                  td style="background-color:black;text-align: center;" width="600" height="33"
                    = link_to (image_tag 'http://www.ziba-style.com/assets/css/logo.png', alt:'Ziba Style', width:'76', height:'33'), "http://www.ziba-style.com", title:'Ziba Style'
                  td width="25" height="33" style="background-color:black;"
                    a
                tr
                  td width="25" height="20" style="background-color:black;"
                    a
                  td width="600" height="20" style="background-color:black;"
                    table style="border-collapse:collapse;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;background-color:black;"
                      tr
                        td height="20" valign="middle" align="center" style="text-transform:uppercase; letter-spacing:2px;padding-left:20px;" = link_to "COUNTRIES", countries_url, style:"color:white;text-decoration:none;font-size:9px;"
                        td height="20" valign="middle" align="center" style="text-transform:uppercase; letter-spacing:2px;padding-left:20px;" = link_to "APPAREL", category_url(1), style:"color:white;text-decoration:none;font-size:9px;"
                        td height="20" valign="middle" align="center" style="text-transform:uppercase; letter-spacing:2px;padding-left:20px;" = link_to "JEWELRY",  category_url(61), style:"color:white;text-decoration:none;font-size:9px;"
                        td height="20" valign="middle" align="center" style="text-transform:uppercase; letter-spacing:2px;padding-left:20px;" = link_to "ACCESSORIES", category_url(101), style:"color:white;text-decoration:none;font-size:9px;"
                        td height="20" valign="middle" align="center" style="text-transform:uppercase; letter-spacing:2px;padding-left:20px;" = link_to "OBJETS D'ART", category_url(141), style:"color:white;text-decoration:none;font-size:9px;"
                        td height="20" valign="middle" align="center" style="text-transform:uppercase; letter-spacing:2px;padding-left:20px;"
                          span style="color:#ffffff;text-decoration:none;font-size:9px;" = link_to "WOMEN/MEN", countries_url, style:"color:#ffffff;text-decoration:none;font-size:9px;"
                  td width="25" height="20" style="background-color:black;"
                    a
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
                    a
              table
                tr
                  td height="10"
                    table style="border-collapse:collapse;display:inline;"
                      tr
                        td width="25"
                          a
                        td width="600" style="font-size:14px;font-weight:100;line-height:20px;letter-spacing:0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;text-align:center;"
                          p style="margin:0px;height:50px;padding-top:30px;font-size:30px;font-weight: 100;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;text-align:center;" WELCOME.
                          p style="margin:0px;height:50px;font-size:24px;font-weight:100;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;text-align:center;" WE'VE BEEN WAITING FOR YOU.
                          p style="height:89px;" = image_tag "http://www.ziba-style.com/assets/email_approve_boutique_img.png", alt:'Welcome Image', style:'display:inline-block;', width:'200', height:'89'
                          table style="border-collapse:collapse;"
                            tr
                              td width="150"
                                a
                              td width="300"
                                p style="padding-top:20px;padding-bottom:20px;font-size:28px;line-height:30px;font-weight: 100;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;text-align:center;" READY TO DISCOVER WHAT WE'RE ALL ABOUT?
                              td width="150"
                                a
                          table style="border-collapse:collapse;"
                            tr
                              td width="100"
                                a
                              td width="400"
                                p style="padding-bottom:10px;font-size:16px;color:gray;text-align:center;" Join us today to experience the most exciting shopping trips around the world.
                              td width="100"
                                a
                          table style="border-collapse:collapse;"
                            tr
                              td width="150" align="left"
                                = link_to (image_tag "http://www.ziba-style.com/assets/email_view_my_account_btn.png", alt:'My Account', style:'display:block;', width:'198', height:'43'), "http://www.ziba-style.com/account", title:'My Account'
                              td width="300" align="center"
                                = image_tag "http://www.ziba-style.com/assets/email_view_jewelry.jpg", alt:'view jewelry', width: 200, height: 200, style:'display:block;'
                              td width="150" align="right"
                                = link_to (image_tag "http://www.ziba-style.com/assets/email_view_shop_word_btn.png", alt:'Shop The World', style:'display:block;', width:'198', height:'43'), "http://www.ziba-style.com", title:'Shop The World'
                        td width="25"
                          a
                      tr
                        td width="25"
                          a
                        td width="600" style="font-size: 14px;font-weight: 100;line-height: 20px;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;text-align:center;"
                          p style="line-height:1.4;" ZIBA Style - the online shopping destination that connects you with the best in locally inspired luxury from around the world.
                          p style="line-height:1.4;" From Mumbai to Miami and Bali to Beirut, our curators bring you the world's most unique luxury goods, allowing you to shop directly from exotic designers worldwide.
                        td width="25"
                          a
                      tr
                        td width="650" height="10" colspan="3"
                          a
              table
                tr
                  td height="10"
                    a
              table style="border-collapse:collapse;background-color:#000000;"
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
                    a
                tr
                  td width="25" height="33"
                    a
                  td width="600" height="33"
                    table style="display:inline;border-collapse:collapse;"
                      tr
                        tr
                        td height="33" = link_to (image_tag "http://www.ziba-style.com/assets/css/face-icon.png", style:"display:block;", alt:'fb', width:'6', height:'10'), "https://www.facebook.com/ZibaStyle", title:'fb'
                        td height="33" style="padding-left:8px;" = link_to (image_tag "http://www.ziba-style.com/assets/css/twitter-icon.png", style:"display:block;", alt:'tw', width:'6', height:'10'), "https://twitter.com/#!/ZIBASTYLE", title:'tw'
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "About", about_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;"
                          span style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;" = link_to "Style Directory", style_directory_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Privacy", privacy_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Terms", terms_of_service_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Shipping & Returns", shipping_and_returns_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;"
                          span = link_to "FAQ", faq_url, style:"color:#ffffff;text-decoration:none;font-size:8px;padding-left:20px;"
                        td height="33" valign="middle" align="right" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Contact", contact_us_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                  td style="background-color:black;" width="25" height="33"
                    a
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
                    a
      p style="color:#a6a6a6;margin:10px;" This email is being sent to you by ZIBA Style Inc

app/views/notifier/send_designer_boutique_has_been_approved_notification.html.slim
doctype transitional
html
  head
    <meta content="text/html; charset=UTF-8; format='flowed'" http-equiv="Content-Type" />
    <style type="text/css">.ReadMsgBody {width: 100%;} .ExternalClass {width: 100%;}</style>
    title ZIBA Style
  body
    div style="text-align:center;"
      p style="color:#a6a6a6" To ensure delivery to your inbox, please add <a href="mailto:support@ziba-style.com">support@ziba-style.com</a> to your address book.
      div style="margin-left:auto;margin-right:auto;width:100%;text-align:left;"
        table align="center" style="border-collapse:collapse;border-left:solid 1px black;border-right:solid 1px black;margin:auto;" width="650"
          tr
            td style="padding:0;"
              table style="border-collapse:collapse;"
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
                tr
                  td style="background-color:black;" width="287" height="33"
                  td style="background-color:black;line-height:0;" width="76" height="33"
                    = link_to (image_tag 'http://www.ziba-style.com/assets/css/logo.png', style:"display:block;", alt:'Ziba Style', width:76, height:33), "http://www.ziba-style.com", title:'Ziba Style'
                  td style="background-color:black;" width="287" height="33"
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
              table
                tr
                  td height="10" width="650"
              table style="display:inline;border-collapse:collapse;"
                tr
                  td width="25"
                  td width="600" style="font-size: 14px;font-weight: 100;line-height: 20px;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;text-align:center;"
                    p style="font-size:30px;" Welcome.
                    p style="font-size:24px;" We're excited to have you here with us.
                    p style="height:89px;" = image_tag "http://www.ziba-style.com/assets/email_approve_boutique_img.png", style:"display:inline-block;", alt:'approve boutique', width:'200', height:'89'
                    p style="font-size:18px;" Dear #{@designer.fname},
                    p style="font-size:18px;" Congratulations - your ZIBA Style boutique has been approved.
                    p style="font-size:18px;" Welcome to our international design community.
                    p style="font-size:18px;" Now sit back and let us take care of you.
                    p style="height:43px;" = link_to (image_tag "http://www.ziba-style.com/assets/email_view_my_boutique_btn.png", style:"display:inline-block;", alt:'view my boutique', width:'198', height:'43'), designer_url(@designer), title:'view my boutique'
                    p style="font-size:18px;" For any questions, do not hesitate to contact us directly at
                    p style=" font-size:18px;" = link_to "designer.concierge@ziba-style.com", "mailto:designer.concierge@ziba-style.com"
                  td width="25"
                tr
                  td width="650" height="10" colspan="3"
              table
                tr
                  td height="10" width="650"
              table style="border-collapse:collapse;color:#ffffff;" bgcolor="#000000"
                tr
                  td width="650" height="15" colspan="3"
                tr
                  td width="25"
                  td width="600"
                    table style="display:block;border-collapse:collapse;"
                      tr
                        td width="300" align="left"
                          = link_to (image_tag "http://www.ziba-style.com/assets/email_view_my_account_btn.png", style:"display:block;", width:'198', height:'43', alt:'My Account'), "http://www.ziba-style.com/account", title:'My Account'
                        td width="300" align="right"
                          = link_to (image_tag "http://www.ziba-style.com/assets/email_view_shop_word_btn.png", style:"display:block;", width:'198', height:'43', alt:'Shop The World'), "http://www.ziba-style.com", title:'Shop The World'
                  td width="25"
                tr
                  td width="25" height="33"
                  td width="600" height="33"
                    table style="display:block;border-collapse:collapse;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;"
                      tr
                        td height="33" = link_to (image_tag "http://www.ziba-style.com/assets/css/face-icon.png", style:"display:block;", alt:'fb', width:'6', height:'10'), "https://www.facebook.com/ZibaStyle", title:'fb'
                        td height="33" style="padding-left:8px;" = link_to (image_tag "http://www.ziba-style.com/assets/css/twitter-icon.png", style:"display:block;", alt:'tw', width:'6', height:'10'), "https://twitter.com/#!/ZIBASTYLE", title:'tw'
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "About", about_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;"
                          span style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;" = link_to "Style Directory", style_directory_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Privacy", privacy_url, style:"color:#ffffff;text-decoration:none;font-size:8px;text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Terms", terms_of_service_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Shipping & Returns", shipping_and_returns_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="center" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span style="color:#ffffff !important;text-decoration:none;font-size:8px;" = link_to "FAQ", faq_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                        td height="33" valign="middle" align="right" style="text-transform:uppercase;letter-spacing:2px;padding-left:20px;"
                          span = link_to "Contact", contact_us_url, style:"color:#ffffff;text-decoration:none;font-size:8px;"
                  td style="background-color:black;" width="25" height="33"
                tr
                  td style="background-color:black;" width="650" height="15" colspan="3"
                    a
      p style="color:#a6a6a6" This email is being sent to you by ZIBA Style Inc

app/views/notifier/send_product.html.slim
table style="border-collapse:collapse;"
  tr
    td width="25"
    td width="600" style="font-size: 14px;font-weight: 100;line-height: 20px;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;color:gray;"
      


      table style="border-collapse:collapse;" width="600"
        tr
          td width="400" style="border-bottom:solid 1px grey"
            p style="font-size: 14px;font-weight: 100;font-family:'HelveticaLightRegular',Helvetica,arial,sans-serif;color:gray;"
              | #{@invitation.from_user.fname} #{@invitation.from_user.lname} has shared a style with you
          td width="200" style="border-bottom:solid 1px grey" align="right"
             = link_to (image_tag "http://www.ziba-style.com/assets/email_view_buy_now_btn.png", alt:'Buy Now'), product_url(@product), title:'Buy Now'

      p Message from #{@invitation.from_user.fname} #{@invitation.from_user.lname}

      p #{simple_format @invitation.message}

      table style="border-collapse:collapse;"
        tr
          td width="220"
            = (image_tag @product.primary_image.attachment.url, style:"width:190px;", alt:'Product Image') if @product.primary_image
          td width="380" valign="top"
            p #{@product.name}
            p by #{@product.designer.designer_name} (#{@product.designer.country.name if @product.designer.country})
            p 
              | Inspiration behind this piece: 
              br
              #{@product.short_description}
            table
              tr
              td
                p #{link_to (image_tag "http://www.ziba-style.com/assets/email_view_buy_now_btn.png", alt:'Buy Now'), product_url(@product), title:'Buy Now'}
              td
                p style="font-size:12px;" Not a member? Use this #{link_to "invitation", customer_sign_up_with_invitation_url(@invitation.token, {email: @invitation.email})} to access the site

        tr
          td width="200" height="15" style="border-bottom:solid 1px grey"
          td width="400" height="15" style="border-bottom:solid 1px grey"
        tr
          td width="200" height="20"
          td width="400" height="20"

      table style="border-collapse:collapse;"
        tr
          td width="195" valign="top"
            p style="font-size: 14px;font-weight: 100;line-height: 20px;letter-spacing: 0px;font-family:'HelveticaLightRegular', Helvetica, arial, sans-serif;font-style:italic;" #{link_to "View more by this designer", designer_url(@product.designer)}

          - @product.designer.products.featured.limit(3).each do |product|
            - if product.primary_image
              td width="135" valign="top"
                = link_to "#{image_tag product.primary_image.attachment.url, style:"width:110px", alt:'Product Image'}<p style=\"color:black;text-decoration:none;\">#{product.name}</p>".html_safe, product_url(product), style:"text-decoration:none;", title:'Product Image'

        tr
          td height="15" colspan="4"
    td width="25"
  tr  
    td width="650" height="3" colspan="3"