config/routes.rb
ZIBAStyle::Application.routes.draw do

  mount Mercury::Engine => '/'

  resources :home_page_entities
  resources :home_page, only: :index do 
    collection {
      get :admin
      post :admin
    }
  end

  WepayRails.routes(self)
  
  resources :categories
  match 'categories/:id/:category_id' => 'categories#show'
  
  resources :contacts, only: [:index, :create, :show] do
    collection { get :contact_us, :request_invitation }
  end
  resources :credits
  resources :designers, only: [:index, :show, :edit, :update ] do
    collection { get :activate, :boutique, :sales_report, :force_apply, :videos, :settings, :upload_designers_page_banner
                 put  :deactivate_boutique_request, :upload_designers_page_banner
                 post :sales_report }
    member { get :detailed_view } 
  end

  match '/designers/:id/upload_banner' => 'designers#upload_banner', as: 'upload_banner'

  resources :designer_orders, only: [:index, :show, :edit, :update ]
  resources :designer_videos
  resources :countries do
    member { post :mercury_update
             get :history }
  end

  resources :editor_picks
  
  match '/shopping_bag'     => 'cart#index',  via: :get,  as: 'shopping_bag'
  match '/shopping_bag'     => 'cart#create', via: :post, as: 'shopping_bag'
  match '/shopping_bag/:id' => 'cart#update', via: :put,  as: 'shopping_bag'
  
  resources :cart, only: [:index, :create, :update ]
  
  resources :feedbacks, only: [:index, :new, :create ]
  resources :file_attachments, only: [:update, :show]

  match '/file_attachments/:id/crop_studio/:style', to: 'file_attachments#crop_studio', as: :crop_style

  resources :invitations, only: [:index, :create ]
  resources :orders, except: [:create, :new, :destroy ]
  resources :pages do
    member { post :mercury_update }
  end

  match '/export_products' => 'products#export_products'
  match '/export_users' => 'users#export_users'
  resources :products do
    member { get :share, :share_by_email, :crop_studio, :size_chart }
  end
  resources :returns, except: :delete do 
    member { put :restock }
  end
  
  resources :sales, only: [:index, :edit, :update]

  match '/browsing_gender/:gender' => 'users#browsing_gender', as: 'browsing_gender', via: :put

  resources :search, only: [:index, :create]

  match 'products/:id/sizes'    => 'products#sizes', as: :products_sizes
  match 'products/:id/shipping' => 'products#edit', action_type: "shipping", as: :products_shipping

  match '/checkout'           => 'orders#checkout',           via: [:get,:post]
  match '/checkout'           => 'orders#update',             via: [:put]
  match '/validate_checkout'  => 'orders#validate_checkout'
  match '/cancel_checkout'    => 'orders#cancel_checkout',    via: :post
  match '/order_complete'     => 'orders#order_complete',     via: :get
  match '/review_orders'      => 'feedbacks#customer_index',  via: :get

  match '/designers_feedbacks' => 'feedbacks#index', user_type: "designer", via: :get
  match '/designer_returns'    => 'returns#designer_returns', via: :get
  match '/style_directory'     => 'designers#style_directory', via: :get
  match '/become_designer'     => 'designers#become_designer', via: :get, as: :become_designer
  match '/become_designer'     => 'designers#switch_to_designer', via: :post, as: :become_designer
  match '/designer_accepted/:authentication_token' => 'designers#accepted', via: :get, as: :designer_accepted

  match '/about'                => 'pages#show',                id: "about",                via: :get
  match '/style_directory'      => 'pages#show',                id: "style",                via: :get
  match '/privacy'              => 'pages#show',                id: "privacy",              via: :get
  match '/terms_of_service'     => 'pages#show',                id: "terms_of_service",     via: :get
  match '/membership'           => 'pages#show',                id: "membership",           via: :get
  match '/faq'                  => 'pages#show',                id: "faq",                  via: :get
  match '/shipping_and_returns' => 'pages#show',                id: "shipping_and_returns", via: :get
  match '/blog'                 => 'pages#blog',                id: "blog",                 via: :get
 
  match '/about'                => 'pages#update',                id: "about",                via: :put
  match '/style_directory'      => 'pages#update',                id: "style",                via: :put
  match '/privacy'              => 'pages#update',                id: "privacy",              via: :put
  match '/terms_of_service'     => 'pages#update',                id: "terms_of_service",     via: :put
  match '/membership'           => 'pages#update',                id: "membership",           via: :put
  match '/faq'                  => 'pages#update',                id: "faq",                  via: :put
  match '/shipping_and_returns' => 'pages#update',                id: "shipping_and_returns", via: :put
  
  match '/contact_us'       => 'contacts#contact_us',                                 via: :get
  match '/engage_with_us'   => 'contacts#engage_with_us',                             via: :get
 
 
  match 'admin/approve_designers'   => 'admin#approve', action_name: "approve_designers",   via: [:get, :post]
  match 'admin/authorize_designers' => 'admin#approve', action_name: "authorize_designers", via: [:get, :post]
  match 'admin/approve_products'    => 'admin#approve', action_name: "approve_products",    via: [:get, :post]
  match 'admin/approve_videos'      => 'admin#approve', action_name: "approve_videos",      via: [:get, :post]
  match 'admin/orders'              => 'orders#index',  user_type: "admin",                 via: :get
  match 'admin/returns'             => 'returns#index', user_type: "admin",                 via: :get
  match 'admin/returns/:id/edit'    => 'returns#edit',  user_type: "admin",                 via: :get, as: :admin_edit_return
  match 'admin/products'            => 'products#index',user_type: "admin",                 via: :get
  match 'admin/countries'           => 'countries#admin_index',                             via: :get, as: :admin_countries
  match 'admin/switch_to_designer'  => 'admin#switch_to_designer',                          via: :post
  match 'admin/switch_to_admin'     => 'admin#switch_to_admin',                             via: :post

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords"  } 
  devise_scope :user do
    root to: 'home_page#index'
    match 'designer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :designer ], via: :get
    match 'designer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :designer ], via: :post
    match 'customer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :customer ], via: :get
    match 'customer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :customer ], via: :post
    match '/invite/:invitation_token' => 'users/registrations#new',    role: User::ROLE[ :customer ], as: "customer_sign_up_with_invitation"
    match '/account'                  => 'users/registrations#edit',   view: "account", via: :get
    match '/shipping_info'            => 'users/registrations#edit',   view: "shipping", via: :get
    match '/designer_accepted_registration/:authentication_token' => 'users/registrations#edit', via: :get, as: :designer_accepted_registration

  end
 
  resources :users, only: [:index, :edit, :update]

  match '*not_found', to: 'errors#error_404'
  

end

app/views/admin/_switch_to_admin.html.slim
- if admin_as_designer?
  li
    = form_tag "/admin/switch_to_admin" do 
      = link_to "Logged In as #{current_user.designer_name}", "#", class: "credit_nav_link hover", onclick: "return false"
      = submit_tag "Back To Admin", style: "margin-left:5px"

app/views/admin/_switch_to_designer.html.slim
- if current_user_is_admin?
  li style="margin-bottom:10px"
    = form_tag "/admin/switch_to_designer" do 
      = link_to "Switch To Designer", "#", class: "credit_nav_link hover", onclick: "return false"
      = select "admin", "designer_id", User.designers(status: User::STATUS.values_at(:authorized, :pending_approval, :approved)).where{confirmed_at != nil}.collect {|p| [ p.designer_name, p.id ] }, {:include_blank => 'None'}
      = submit_tag "Switch"
      br

app/views/admin/approve.html.slim
- title params[:action_name]
- meta_description "admin #{params[:action_name]} description."
- meta_keywords params[:action_name]
h1=@title
- if @xls.present?
  = link_to @xls, export_products_path(format: "xls")
table.dashboard_table#approval_table
  tr 
  - @data[:columns].each do |key, column_name|
    th = "#{column_name}"
  - @data[:entities].each do |entity|
    tr
      - @data[:columns].each do |key, column_name|
        td(style="#{ (key == :action) ? "width:100px" : "" }")
          - unless key == :action
            - if key == :email or (key == :name and entity.kind_of?(Product))
              = link_to(entity[key], designer_path(entity), target: "_blank" ) if entity.kind_of?(User)
              = link_to(entity[key], product_path(entity),  target: "_blank")  if entity.kind_of?(Product)
            - elsif key == :portfolio
              p 
                = link_to 'View Portfolio', /^http/.match(entity.designer_portfolio_url) ? entity.designer_portfolio_url : "http://#{entity.designer_portfolio_url}"
              ul style='list-style:none;'
                - entity.portfolio_docs.each do |doc|
                  li
                    = link_to "download doc", doc.attachment.url


            - else
              = entity[key]
          - else
            p= link_to("Detailed Designer View", detailed_view_designer_path(entity), target: "_blank") if entity.kind_of?(User)
            p= link_to("View Product", product_path(entity),   target: "_blank") if entity.kind_of?(Product)
            p= link_to("Edit Product", edit_product_path(entity),   target: "_blank") if entity.kind_of?(Product)
            p= link_to "activate", @data[:url], data: { entity_id: entity.id }, class: :admin_approve_link