config/routes.rb
ZIBAStyle::Application.routes.draw do

  mount Mercury::Engine => '/'

  resources :home_page_entities
  resources :home_page, only: :index do 
    collection {
      get :admin
      post :admin
    }
  end

  WepayRails.routes(self)
  
  resources :categories
  match 'categories/:id/:category_id' => 'categories#show'
  
  resources :contacts, only: [:index, :create, :show] do
    collection { get :contact_us, :request_invitation }
  end
  resources :credits
  resources :designers, only: [:index, :show, :edit, :update ] do
    collection { get :activate, :boutique, :sales_report, :force_apply, :videos, :settings, :upload_designers_page_banner
                 put  :deactivate_boutique_request, :upload_designers_page_banner
                 post :sales_report }
    member { get :detailed_view } 
  end

  match '/designers/:id/upload_banner' => 'designers#upload_banner', as: 'upload_banner'

  resources :designer_orders, only: [:index, :show, :edit, :update ]
  resources :designer_videos
  resources :countries do
    member { post :mercury_update
             get :history }
  end

  resources :editor_picks
  
  match '/shopping_bag'     => 'cart#index',  via: :get,  as: 'shopping_bag'
  match '/shopping_bag'     => 'cart#create', via: :post, as: 'shopping_bag'
  match '/shopping_bag/:id' => 'cart#update', via: :put,  as: 'shopping_bag'
  
  resources :cart, only: [:index, :create, :update ]
  
  resources :feedbacks, only: [:index, :new, :create ]
  resources :file_attachments, only: [:update, :show]

  match '/file_attachments/:id/crop_studio/:style', to: 'file_attachments#crop_studio', as: :crop_style

  resources :invitations, only: [:index, :create ]
  resources :orders, except: [:create, :new, :destroy ]
  resources :pages do
    member { post :mercury_update }
  end

  match '/export_products' => 'products#export_products'
  match '/export_users' => 'users#export_users'
  resources :products do
    member { get :share, :share_by_email, :crop_studio, :size_chart }
  end
  resources :returns, except: :delete do 
    member { put :restock }
  end
  
  resources :sales, only: [:index, :edit, :update]

  match '/browsing_gender/:gender' => 'users#browsing_gender', as: 'browsing_gender', via: :put

  resources :search, only: [:index, :create]

  match 'products/:id/sizes'    => 'products#sizes', as: :products_sizes
  match 'products/:id/shipping' => 'products#edit', action_type: "shipping", as: :products_shipping

  match '/checkout'           => 'orders#checkout',           via: [:get,:post]
  match '/checkout'           => 'orders#update',             via: [:put]
  match '/validate_checkout'  => 'orders#validate_checkout'
  match '/cancel_checkout'    => 'orders#cancel_checkout',    via: :post
  match '/order_complete'     => 'orders#order_complete',     via: :get
  match '/review_orders'      => 'feedbacks#customer_index',  via: :get

  match '/designers_feedbacks' => 'feedbacks#index', user_type: "designer", via: :get
  match '/designer_returns'    => 'returns#designer_returns', via: :get
  match '/style_directory'     => 'designers#style_directory', via: :get
  match '/become_designer'     => 'designers#become_designer', via: :get, as: :become_designer
  match '/become_designer'     => 'designers#switch_to_designer', via: :post, as: :become_designer
  match '/designer_accepted/:authentication_token' => 'designers#accepted', via: :get, as: :designer_accepted

  match '/about'                => 'pages#show',                id: "about",                via: :get
  match '/style_directory'      => 'pages#show',                id: "style",                via: :get
  match '/privacy'              => 'pages#show',                id: "privacy",              via: :get
  match '/terms_of_service'     => 'pages#show',                id: "terms_of_service",     via: :get
  match '/membership'           => 'pages#show',                id: "membership",           via: :get
  match '/faq'                  => 'pages#show',                id: "faq",                  via: :get
  match '/shipping_and_returns' => 'pages#show',                id: "shipping_and_returns", via: :get
  match '/blog'                 => 'pages#blog',                id: "blog",                 via: :get
 
  match '/about'                => 'pages#update',                id: "about",                via: :put
  match '/style_directory'      => 'pages#update',                id: "style",                via: :put
  match '/privacy'              => 'pages#update',                id: "privacy",              via: :put
  match '/terms_of_service'     => 'pages#update',                id: "terms_of_service",     via: :put
  match '/membership'           => 'pages#update',                id: "membership",           via: :put
  match '/faq'                  => 'pages#update',                id: "faq",                  via: :put
  match '/shipping_and_returns' => 'pages#update',                id: "shipping_and_returns", via: :put
  
  match '/contact_us'       => 'contacts#contact_us',                                 via: :get
  match '/engage_with_us'   => 'contacts#engage_with_us',                             via: :get
 
 
  match 'admin/approve_designers'   => 'admin#approve', action_name: "approve_designers",   via: [:get, :post]
  match 'admin/authorize_designers' => 'admin#approve', action_name: "authorize_designers", via: [:get, :post]
  match 'admin/approve_products'    => 'admin#approve', action_name: "approve_products",    via: [:get, :post]
  match 'admin/approve_videos'      => 'admin#approve', action_name: "approve_videos",      via: [:get, :post]
  match 'admin/orders'              => 'orders#index',  user_type: "admin",                 via: :get
  match 'admin/returns'             => 'returns#index', user_type: "admin",                 via: :get
  match 'admin/returns/:id/edit'    => 'returns#edit',  user_type: "admin",                 via: :get, as: :admin_edit_return
  match 'admin/products'            => 'products#index',user_type: "admin",                 via: :get
  match 'admin/countries'           => 'countries#admin_index',                             via: :get, as: :admin_countries
  match 'admin/switch_to_designer'  => 'admin#switch_to_designer',                          via: :post
  match 'admin/switch_to_admin'     => 'admin#switch_to_admin',                             via: :post

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords"  } 
  devise_scope :user do
    root to: 'home_page#index'
    match 'designer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :designer ], via: :get
    match 'designer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :designer ], via: :post
    match 'customer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :customer ], via: :get
    match 'customer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :customer ], via: :post
    match '/invite/:invitation_token' => 'users/registrations#new',    role: User::ROLE[ :customer ], as: "customer_sign_up_with_invitation"
    match '/account'                  => 'users/registrations#edit',   view: "account", via: :get
    match '/shipping_info'            => 'users/registrations#edit',   view: "shipping", via: :get
    match '/designer_accepted_registration/:authentication_token' => 'users/registrations#edit', via: :get, as: :designer_accepted_registration

  end
 
  resources :users, only: [:index, :edit, :update]

  match '*not_found', to: 'errors#error_404'
  

end

app/helpers/designers_helper.rb
module DesignersHelper
	def designer_banner_pic(designer)
		designer.banner_pic.blank? ? image_tag("css/banner.jpg", width: "960", height: "180") : image_tag(designer.banner_pic.attachment.url(:banner), width: "960", height: "180", alt: "Banner Photo")
	end

	def designer_profile_pic(designer)
		designer.profile_pic.blank? ? image_tag("css/bio1.jpg", width: "150", height: "150") : image_tag(designer.profile_pic.attachment.url(:profile), width: "150", height: "150", alt: "Profile Photo")
	end
end

app/views/designers/_feedbacks.html.slim
- if @designer.average_feedback_rating
  .featured.feedback
    h5 FEEDBACK
    p
      | Customers so far have given
    span.feedback
     = render partial: "/shared/feedback_stars", locals: {opts: {disabled: :disabled, rating: @designer.average_feedback_rating, feedback_id: @designer.average_feedback_rating}}
.cl

app/views/designers/_profile.html.slim
.banner
  = designer_banner_pic(@designer)
/! Bio
.bio
  .image
    = designer_profile_pic(@designer)
  .text
    .title
      .left
        h6 = @designer.designer_name
        p 
          = "#{@designer.designer_city}, #{!@designer.designer_country.blank? ? @designer.designer_country.name : ""}"
          = image_tag @designer.designer_country.flag.url(:small) unless @designer.designer_country.blank?
        / p
          / span
          /   | Follow this
          /   br
          /   | designer on
          / a href="#"
          /   img alt="" src="/assets/css/twitter.png"  
          / span.cl &nbsp;
      .cl &nbsp;

    .scroll-designer-pane
      .biography
        = @designer.designer_biography.try(:html_safe)
  ul.navigation
    li
      span.navigation_sub_titles
        | Collection
      br
      - if user_signed_in?
        = link_to "Shop Online", "#", class: "designer_nav", "data-action" => "featured_pieces"
      - else
        = link_to "Featured Pieces", "#", class: "designer_nav", "data-action" => "featured_pieces"
    li
      span.navigation_sub_titles
        | Seen On
      br
      = link_to "Celebrity Style", "#", class: "designer_nav", "data-action" => "as_seen_on"
    li
      span.navigation_sub_titles
        | Ziba.tv
      br
      = link_to "Runway Videos & More", "#", class: "designer_nav", "data-action" => "videos"

  .cl &nbsp;
  / = link_to "", engage_with_us_path, class: "stamp"
  / .cl &nbsp;

app/views/designers/_videos.html.erb
<ul>
  <% print_switch = true %>
  <% own_index = 0 %>
  <% videos.each do |video| %>
    <%= (print_switch or videos.count <= 3) ? "<li>".html_safe : "" %>
      <div class="video <%= (print_switch or videos.count <= 3) ? "" : "hidden_video" %>">

        <!-- <div class="container"> -->
          <!-- <%= link_to video.url, video.url, class: "#{ ((print_switch and own_index < 3) or videos.count <= 3) ? "oembed" : ""}" %> -->
        <!-- </div> -->
        <%= video.oembed_resource.html.html_safe %>
        <br>
        <%= video.name %>
        <div class="cl"></div>
      </div>
    <%= (print_switch and videos.count > 3) ? "" : "</li>".html_safe %>
    <% print_switch = print_switch ? false : true %>
    <% own_index = own_index+1 if (print_switch or videos.count < 3)  %>
  <% end %>
</ul>
<div class="cl"></div>

app/views/designers/activate.html.slim
- title "Activate Boutique"
- meta_description "Activate Boutique description."
- meta_keywords "Activate Boutique"
= link_to "Go to my Designer Boutique", designer_path(@designer), class: "link_to_designer_page"

- if @designer.designer_status == User::STATUS[:approved]
  = form_for @designer, url: edit_designer_path do |f|
    p TODO: DESCRIPTION OF WHAT THIS DO
    .field
      .checkbox
        = f.check_box :designer_active
        = f.label :designer_active
    .cl
    .buttons= f.submit "Save", class: "button dark"
- else
  p Your boutique is not approved yet, you will be able to activate it as soon as your account has been approved

app/views/designers/boutique.html.slim
- title "Boutique"
- meta_description "Boutique description."
- meta_keywords "Boutique"
.cl

= link_to "Go to my Designer Boutique", designer_path(@designer), class: "link_to_designer_page"
/ h2 My Designer Profile
  
- if @disable
  .designer_unlock_boutique
    = form_for(@designer, :url => deactivate_boutique_request_designers_path) do |f|
      p To modify your profile, you must submit a request to the ZIBA team. You will then be able to make changes.
      = f.submit "Send Request", class: "button dark"
  .cl
= form_for(@designer, :url => designer_path(@designer), :html => { :multipart => true }) do |f|

  - if @designer.errors.any?
    #error_explanation
      h2
        = pluralize(@designer.errors.count, "error")
        | prohibited your boutique from being saved:
      ul
        - @designer.errors.full_messages.each do |msg|
          li= msg


    
  = f.fields_for :banner_pic do |file|
    .field.designer.banner_pic
      = designer_banner_pic(@designer)
      = file.file_field :attachment, disabled: @disable
    .cl

  .cl



  .left.designer_boutique

    = f.fields_for :profile_pic do |file|
      .field
        = designer_profile_pic(@designer)
        .cl
        = file.file_field :attachment, disabled: @disable
      .cl    

  .right.designer_boutique

    .field
      = f.label :designer_name
      = f.text_field :designer_name, disabled: @disable, class: "blink gray-shadow", title: "Label Name"
    .cl

    .designer_location
      .field
        = f.label :designer_city
        br
        = f.text_field :designer_city, disabled: @disable, class: "left blink gray-shadow", title: "City"
      .field.designer_state_id_wrapper
        = f.label :designer_state_id
        br
        = f.select :designer_state_id, State.order{states.code}.all.collect{|c| [c.name, c.id] }, { include_blank: "--- State ---" }, disabled: @disable, class: "left"
      .field
        = f.label :designer_country_id
        br
        = f.select :designer_country_id, Country.order{countries.name}.all.collect{|c| [c.name, c.id] }, { include_blank: "--- Country ---" }, disabled: @disable, class: "designer_country_id_select left"

    .cl
    .field
      = f.label :designer_ships_from
      br
      = f.text_field :designer_ships_from, disabled: @disable, class: "left blink gray-shadow", title: "Ships From"
    .cl
    .field
      = f.label :designer_biography
      = f.text_area :designer_biography, disabled: @disable, class: "blink gray-shadow", title: "Biography"
    .cl
  
  .cl

  .designer_boutique.gray.gray-shadow

    / .field
    /   = f.label :designer_paypal
    /   = f.text_field :designer_paypal, disabled: @disable
    / .cl

    p.indicate-tax-prompt Please indicate the sales tax applicable to items sold from your boutique
    .field.narrow
      = f.label :designer_tax_rate
      = f.text_field :designer_tax_rate, disabled: @disable
      span.percentage %
      a.more-info.domestic href="#"
        img alt="" src="/assets/css/see-more.png"

    .cl

    .field.int_tax_rate_wrapper.narrow
      = f.label :designer_int_tax_rate
      = f.text_field :designer_int_tax_rate, disabled: @disable
      span.percentage %
      a.more-info.international href="#"
        img alt="" src="/assets/css/see-more.png"

    .cl  

  - if admin_as_designer? or @designer.designer_status == User::STATUS[:authorized] #TODO: there was a problem here - make sure this is the right code
    .buttons= f.submit "Save", class: "button pink", disabled: @disable
  .cl

- if @designer.designer_status == User::STATUS[:authorized] #TODO: there was a problem here - make sure this is the right code
  = form_for(@designer, :url => designer_path(@designer)) do |f|
    = f.hidden_field :designer_request_approval

    / .field
    /   .checkbox
    /     = f.check_box :terms_of_service
    /     = f.label :terms_of_service, "by checking I accept the #{link_to "Terms of service", "/terms_of_service"}".html_safe

    .buttons.arrange-right= f.submit "Submit", class: "button pink"

.cl

- content_for(:javascript_includes) do
  javascript:
    var usa_country_id = #{::USA_COUNTRY_ID}; 
    $(function(){ 
    adapt_boutique_form(#{@designer.designer_country_id}) 
    $("a.more-info.domestic").qtip({
        content: {
          text: "Please indicate the relevant domestic sales tax you would like to collect on any domestic sales you make."
        },
        position: {
          my: 'bottom center',
          at: 'top center'
        },
        style: {
          classes: 'ui-tooltip-shadow ui-tooltip-youtube'
        }
    });
    $("a.more-info.international").qtip({
        content: {
          text: "If applicable, please indicate the relevant international sales tax you would like to collect on international sales you make."
        },
        position: {
          my: 'bottom center',
          at: 'top center'
        },
        style: {
          classes: 'ui-tooltip-shadow ui-tooltip-youtube'
        }
    });

    
    })

app/views/designers/detailed_view.html.slim
- title "Designer detail view"
- meta_description "Designer detail view description."
- meta_keywords "Designer detail view"
h1 Designer Info

p Designer Name: #{@designer.designer_name}

p Designer Country: #{@designer.designer_country.name unless @designer.designer_country.blank?}

p Designer Biography: #{@designer.designer_biography}

p Designer Active: #{@designer.designer_active}

p Designer Status #{@designer.designer_status}

p Designer City #{@designer.designer_city}

p Designer Paypal: #{@designer.designer_paypal}

p Designer Portfolio: #{@designer.designer_portfolio_url}

p Banner Image
- if @designer.banner_pic.present?
  = image_tag @designer.banner_pic.attachment.url :banner

p = "Profile Image"
- if @designer.profile_pic.present?
  = image_tag @designer.profile_pic.attachment.url :profile

ul
  - @designer.portfolio_docs.each do |doc|
    li
      = link_to "download doc", doc.attachment.url

p Designer Tax Rate: #{@designer.designer_tax_rate}

h1 User Info

p User Email: #{@designer.email}

p User First Name: #{@designer.fname}

p User Last Name: #{@designer.lname}

p User Address 1: #{@designer.address1}

p User Address 2: #{@designer.address2}

p User City: #{@designer.city}

p User Zipcode: #{@designer.zipcode}

p User State: #{@designer.state}

p User Country: #{@designer.country.name unless @designer.country.blank?}

p User Phone: #{@designer.phone}

p User Date Of Birth: #{@designer.dob}

h1 Login Info

p Sign In Count: #{@designer.sign_in_count}

p Last Sign In At: #{@designer.last_sign_in_at}

p Created At: #{@designer.created_at}

app/views/designers/index.html.slim
- title "Designers"
- meta_description "Designer List description."
- meta_keywords "Designers"
- if current_user.try :is_admin?
  - content_for :admin_menu do
    li = link_to 'Edit Banner', upload_designers_page_banner_designers_path

- cache "views_designers_index" do
  .post
    .image
      = image_tag @banner.attachment.url(:banner) unless @banner.blank?
      h2 Designers

  .designer-signup-prompt.designers-page
    |ARE YOU A DESIGNER? > APPLY  
    = link_to "HERE", designer_sign_up_path
    |  TO BE FEATURED

  = form_tag(designers_path, method: 'get', id: 'filterForm') do
    = hidden_field_tag :letter
    .filter
      h5 
        | FILTER BY 
        noscript
          = submit_tag 'Apply'
      ul
        li.filter1
          a COUNTRY
          ul.dd class=(Country.with_designers.count > 10 ? 'countries' : '')
            - Country.with_designers.each do |country|
              li
                label 
                  =' check_box_tag 'country_ids[]', country.id, params_include?(:country_ids, country.id)
                  = country.name
        li.nodrop
          = link_to 'All', designers_path, class: "alpha #{'active' if params[:letter].blank?}", 'data-letter' => ''
          ' &nbsp;&nbsp;
        - ('A'..'Z').to_a.each do |alpha|
          li.nodrop
            = link_to alpha, designers_path.to_s + "?letter=#{alpha}", class: "alpha #{'active' if (params[:letter].present? and params[:letter] == alpha)}", 'data-letter' => alpha

      .cl &nbsp;




  #designers.featured
    - @designers.each_with_index do |designer, i|
      .box.designer
        p
          a href="#{raw designer_path(designer)}"
             = designer_profile_pic(designer)
        p.first
          a href="#{raw designer_path(designer)}"
            = designer.designer_name
            br
            | (#{designer.designer_country.name} #{image_tag designer.designer_country.flag.url(:small), class: "flag_icon"})
  .cl
  #pagination.ajax
    = paginate @designers, window: 3
  .cl


  script id="designers-template" type="text/x-handlebars-template"
    | {{#each designers}}
    .box.designer
      p
        a href=(raw designers_path.to_s + "/{{this.slug}}")
          img src="{{this.profile_pic_url}}"
      p.first
        a href=(raw designers_path.to_s + "/{{this.slug}}")
          | {{this.designer_name}}
          br
          | (
          | {{this.designer_country.name}} 
          img.flag_icon src="{{this.designer_flag_url}}"
          | )
    | {{/each}}

app/views/designers/index.js.erb
$('#designers').html(designers_template({designers: <%= @designers.to_json(methods: [:profile_pic_url, :designer_flag_url], include: :designer_country).html_safe %>}));
$('#pagination.ajax').html('<%= remove_linebreaks(paginate @designers, window: 3) %>');

app/views/designers/settings.html.slim
- title "Boutique settings"
- meta_description "Boutique settings description."
- meta_keywords "Boutique"
h2 Boutique activation/de-activation:

.designer_activate_boutique
  = form_for(@designer, :url => designer_path(@designer)) do |f|
    p
      | PLACE YOUR BOUTIQUE ON VACATION MODE HERE
      br
      | Not going to be available to receive orders during a certain time period?
      br
      | Make your boutique temporarily inactive until you are ready to receive orders again

      br
    .cl
    = f.hidden_field :designer_active, value: (@designer.designer_active? ? 0 : 1)
    = f.submit "#{@designer.designer_active ? "Inactivate" : "Activate"}", class: "button dark"
    .cl

    p
      | You will receive a confirmation email once you place your boutique on vacation mode.
      br
      | You will also receive a notification once you reactivate your boutique.
      br
.cl

app/views/designers/show.html.slim
- title @designer.name
- meta_description "#{@designer.name} description."
- meta_keywords @designer.name
- content_for :admin_menu do
  = render partial: "/shared/add_to_home_page",locals: {entity: @designer}

- content_for :javascript_includes do
  javascript:
    $(function(){
      SEE_ALL.setup(".featured_pieces");
    })

- cache "views/views_designers_show_#{@designer.id}_#{session_gender}" do
  - if current_user.try :is_admin?
    - content_for :admin_menu do
      li = link_to 'Edit Designer Banner', upload_banner_path(@designer.id)
  == render partial: 'profile'
  .designer_boutique_content
    .featured_pieces
      == render partial: "/shared/product_filters", locals: {form_url: designer_path(@designer), categories: @designer.designer_categories(session_gender), designers: []}
      .featured
        == render partial: '/products/products', locals: {products: @products, id: 'products'}
    - unless @designer.products.with_celebrity_pictures.blank? and @designer.designer_status == User::STATUS[:approved] and @designer.designer_active == true and @designer.products.present?
      .featured.as_seen_on
        h5 As seen on
        == render partial: '/products/products', locals: {products: @designer.products.with_celebrity_pictures.random(3), celebrity_pics: true}
    - unless @designer.designer_videos.empty?
      .featured.videos
        - if @designer.designer_videos.count > 3
          = link_to "View More +", "#", class: "more_videos", style: "float:right"
        h5 Videos
        == render partial: '/designers/videos', locals: {videos: @designer.designer_videos}
    /== render partial: 'feedbacks', locals: {designer: @designer }

app/views/designers/style_directory.html.slim
- title "Style Directory"
- meta_description "Style Directory description."
- meta_keywords "Style Directory"
- cache "views_designers_style_directory" do
  #style-directory
    h1 STYLE DIRECTORY
    h2 
      | Products 
      em we feature

    ul#categories
      - @featured_categories.each do |category|
        li
          - if user_signed_in?
            a href=(category_path category)
              = (image_tag category.style_directory_image(:default)) if category.style_directory_image.exists?
              .category-name
                = category.name == 'Apparel' ? 'MENSWEAR / WOMENSWEAR' : category.name.upcase
          - else
            = (image_tag category.style_directory_image(:default)) if category.style_directory_image.exists?
            .category-name
              = category.name == 'Apparel' ? 'MENSWEAR / WOMENSWEAR' : category.name.upcase

    h2
      | Designers 
      em we feature

    .designer-signup-prompt
      em
        |ARE YOU A DESIGNER? > APPLY  
        = link_to "HERE", designer_sign_up_path
        |  TO BE FEATURED

    ul#countries
      - @countries.each_with_index do |country, i|
        li
          .country-name = country.name
          - country.active_designers.sort{|t1,t2|t1.designer_name <=> t2.designer_name}.each do |designer|
            ul#designers
              li = link_to designer.designer_name, designer_path(designer)

app/views/designers/upload_banner.html.slim
- title "Banner"
- meta_description "Banner description."
- meta_keywords "banner"
- if @designer.blank?
  h2 = "Visit a users profile and select 'edit banner' from the admin menu"
- else
  h2 = "Edit banner pic for #{@designer.designer_name}"

  = form_for(@designer, url: upload_banner_path(@designer), multipart: true) do |f|
    = f.fields_for :banner_pic do |file|
      .field.designer.banner_pic
        - if @designer.banner_pic.id
          = designer_banner_pic(@designer)
          
        = file.file_field :attachment, disabled: @disable
        /= link_to 'Crop', file_attachment_path(@designer.banner_pic)
      .cl
    .buttons
      = f.submit "Upload Banner", class: "button dark"
    br
    br
    br

app/views/designers/videos.html.slim
- title "Designer videos"
- meta_description "Designer videos description."
- meta_keywords "Designer videos"
= link_to "Go to my Designer Boutique", designer_path(@designer), class: "link_to_designer_page"
.boutique_videos

  h2.dashboard_index Update videos to your boutique:
  .buttons.dashboard_index
    = link_to "New Video", new_designer_video_path, class: "button dark"
  .cl

  h2.dashboard_index Videos currently appearing on your boutique:
  ul
    - @designer_videos.each do |video|
      li 
        = video.name
        br
        .container
          = link_to video.url, video.url, class: "oembed"
        br
        = video.status == DesignerVideo::STATUS[:pending] ? "This Video is pending for approval" : "This Video has been approved"
        br
        = link_to "Delete this video", designer_video_path(video), method: :delete, confirm: "Do you want to delete this video?"
.cl