config/routes.rb
ZIBAStyle::Application.routes.draw do

  mount Mercury::Engine => '/'

  resources :home_page_entities
  resources :home_page, only: :index do 
    collection {
      get :admin
      post :admin
    }
  end

  WepayRails.routes(self)
  
  resources :categories
  match 'categories/:id/:category_id' => 'categories#show'
  
  resources :contacts, only: [:index, :create, :show] do
    collection { get :contact_us, :request_invitation }
  end
  resources :credits
  resources :designers, only: [:index, :show, :edit, :update ] do
    collection { get :activate, :boutique, :sales_report, :force_apply, :videos, :settings, :upload_designers_page_banner
                 put  :deactivate_boutique_request, :upload_designers_page_banner
                 post :sales_report }
    member { get :detailed_view } 
  end

  match '/designers/:id/upload_banner' => 'designers#upload_banner', as: 'upload_banner'

  resources :designer_orders, only: [:index, :show, :edit, :update ]
  resources :designer_videos
  resources :countries do
    member { post :mercury_update
             get :history }
  end

  resources :editor_picks
  
  match '/shopping_bag'     => 'cart#index',  via: :get,  as: 'shopping_bag'
  match '/shopping_bag'     => 'cart#create', via: :post, as: 'shopping_bag'
  match '/shopping_bag/:id' => 'cart#update', via: :put,  as: 'shopping_bag'
  
  resources :cart, only: [:index, :create, :update ]
  
  resources :feedbacks, only: [:index, :new, :create ]
  resources :file_attachments, only: [:update, :show]

  match '/file_attachments/:id/crop_studio/:style', to: 'file_attachments#crop_studio', as: :crop_style

  resources :invitations, only: [:index, :create ]
  resources :orders, except: [:create, :new, :destroy ]
  resources :pages do
    member { post :mercury_update }
  end

  match '/export_products' => 'products#export_products'
  match '/export_users' => 'users#export_users'
  resources :products do
    member { get :share, :share_by_email, :crop_studio, :size_chart }
  end
  resources :returns, except: :delete do 
    member { put :restock }
  end
  
  resources :sales, only: [:index, :edit, :update]

  match '/browsing_gender/:gender' => 'users#browsing_gender', as: 'browsing_gender', via: :put

  resources :search, only: [:index, :create]

  match 'products/:id/sizes'    => 'products#sizes', as: :products_sizes
  match 'products/:id/shipping' => 'products#edit', action_type: "shipping", as: :products_shipping

  match '/checkout'           => 'orders#checkout',           via: [:get,:post]
  match '/checkout'           => 'orders#update',             via: [:put]
  match '/validate_checkout'  => 'orders#validate_checkout'
  match '/cancel_checkout'    => 'orders#cancel_checkout',    via: :post
  match '/order_complete'     => 'orders#order_complete',     via: :get
  match '/review_orders'      => 'feedbacks#customer_index',  via: :get

  match '/designers_feedbacks' => 'feedbacks#index', user_type: "designer", via: :get
  match '/designer_returns'    => 'returns#designer_returns', via: :get
  match '/style_directory'     => 'designers#style_directory', via: :get
  match '/become_designer'     => 'designers#become_designer', via: :get, as: :become_designer
  match '/become_designer'     => 'designers#switch_to_designer', via: :post, as: :become_designer
  match '/designer_accepted/:authentication_token' => 'designers#accepted', via: :get, as: :designer_accepted

  match '/about'                => 'pages#show',                id: "about",                via: :get
  match '/style_directory'      => 'pages#show',                id: "style",                via: :get
  match '/privacy'              => 'pages#show',                id: "privacy",              via: :get
  match '/terms_of_service'     => 'pages#show',                id: "terms_of_service",     via: :get
  match '/membership'           => 'pages#show',                id: "membership",           via: :get
  match '/faq'                  => 'pages#show',                id: "faq",                  via: :get
  match '/shipping_and_returns' => 'pages#show',                id: "shipping_and_returns", via: :get
  match '/blog'                 => 'pages#blog',                id: "blog",                 via: :get
 
  match '/about'                => 'pages#update',                id: "about",                via: :put
  match '/style_directory'      => 'pages#update',                id: "style",                via: :put
  match '/privacy'              => 'pages#update',                id: "privacy",              via: :put
  match '/terms_of_service'     => 'pages#update',                id: "terms_of_service",     via: :put
  match '/membership'           => 'pages#update',                id: "membership",           via: :put
  match '/faq'                  => 'pages#update',                id: "faq",                  via: :put
  match '/shipping_and_returns' => 'pages#update',                id: "shipping_and_returns", via: :put
  
  match '/contact_us'       => 'contacts#contact_us',                                 via: :get
  match '/engage_with_us'   => 'contacts#engage_with_us',                             via: :get
 
 
  match 'admin/approve_designers'   => 'admin#approve', action_name: "approve_designers",   via: [:get, :post]
  match 'admin/authorize_designers' => 'admin#approve', action_name: "authorize_designers", via: [:get, :post]
  match 'admin/approve_products'    => 'admin#approve', action_name: "approve_products",    via: [:get, :post]
  match 'admin/approve_videos'      => 'admin#approve', action_name: "approve_videos",      via: [:get, :post]
  match 'admin/orders'              => 'orders#index',  user_type: "admin",                 via: :get
  match 'admin/returns'             => 'returns#index', user_type: "admin",                 via: :get
  match 'admin/returns/:id/edit'    => 'returns#edit',  user_type: "admin",                 via: :get, as: :admin_edit_return
  match 'admin/products'            => 'products#index',user_type: "admin",                 via: :get
  match 'admin/countries'           => 'countries#admin_index',                             via: :get, as: :admin_countries
  match 'admin/switch_to_designer'  => 'admin#switch_to_designer',                          via: :post
  match 'admin/switch_to_admin'     => 'admin#switch_to_admin',                             via: :post

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords"  } 
  devise_scope :user do
    root to: 'home_page#index'
    match 'designer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :designer ], via: :get
    match 'designer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :designer ], via: :post
    match 'customer/sign_up'          => 'users/registrations#new',    role: User::ROLE[ :customer ], via: :get
    match 'customer/sign_up'          => 'users/registrations#create', role: User::ROLE[ :customer ], via: :post
    match '/invite/:invitation_token' => 'users/registrations#new',    role: User::ROLE[ :customer ], as: "customer_sign_up_with_invitation"
    match '/account'                  => 'users/registrations#edit',   view: "account", via: :get
    match '/shipping_info'            => 'users/registrations#edit',   view: "shipping", via: :get
    match '/designer_accepted_registration/:authentication_token' => 'users/registrations#edit', via: :get, as: :designer_accepted_registration

  end
 
  resources :users, only: [:index, :edit, :update]

  match '*not_found', to: 'errors#error_404'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  belongs_to :category # for parent relationship
	has_many :subcategories, class_name: :Category # for child relationship
	has_many :categories # for child relationship
  has_many :products, through: :product_categories
	has_many :product_categories 
	has_many :sizes
  
  #friendly_id :name, use:[:slugged, :history]
  friendly_id :name, :use => :scoped, :scope => :category_id
  
  GENDER_TYPES = { women: 1, men: 2, both: 3 }

	# Paperclip, see: https://github.com/thoughtbot/paperclip    
  has_attached_file :banner, :styles => { :small => "150x150>", :banner => "960x180#" },
    storage: :s3,
    s3_protocol: Rails.env.production? ? :https : :http,
    bucket: ZIBAStyle::Application.config.s3_bucket, 
    s3_credentials: ZIBAStyle::Application.config.s3_credentials,
    :path => "/#{Rails.env}/category/banner/:style/:filename"
  
  has_attached_file :style_directory_image, :styles => { :small => "150x150>", :default => "220x270#" },
    storage: :s3,
    bucket: ZIBAStyle::Application.config.s3_bucket, 
    s3_protocol: Rails.env.production? ? :https : :http,
    s3_credentials: ZIBAStyle::Application.config.s3_credentials,
    :path => "/#{Rails.env}/category/style_dir/:style/:filename"    

  has_attached_file :size_chart_man, 
    storage: :s3,
    s3_protocol: Rails.env.production? ? :https : :http,
    bucket: ZIBAStyle::Application.config.s3_bucket, 
    s3_credentials: ZIBAStyle::Application.config.s3_credentials,
    :path => "/#{Rails.env}/category/:id/size_chart/man/:filename"

  has_attached_file :size_chart_woman, 
    storage: :s3,
    s3_protocol: Rails.env.production? ? :https : :http,
    bucket: ZIBAStyle::Application.config.s3_bucket, 
    s3_credentials: ZIBAStyle::Application.config.s3_credentials,
    :path => "/#{Rails.env}/category/:id/size_chart/woman/:filename"

  has_attached_file :size_chart_unisex, 
    storage: :s3,
    s3_protocol: Rails.env.production? ? :https : :http,
    bucket: ZIBAStyle::Application.config.s3_bucket, 
    s3_credentials: ZIBAStyle::Application.config.s3_credentials,
    :path => "/#{Rails.env}/category/:id/size_chart/unisex/:filename"

  has_attached_file :homepage_image, 
    storage: :s3,
    s3_protocol: Rails.env.production? ? :https : :http,
    bucket: ZIBAStyle::Application.config.s3_bucket, 
    s3_credentials: ZIBAStyle::Application.config.s3_credentials,
    path: "/#{Rails.env}/category/:id/homepage/:filename"

  # Sphinx Index
  define_index do
    indexes :name, :sortable => true
  end

  # -- No longer used --
  # def self.subcategories(gender = :women)
  #   unless gender
  #     gender = is_numeric? gender ? gender : GENDER_TYPES[gender]
  #     where{(category_id != nil) & (gender_type.in([gender, GENDER_TYPES[:both]]))}
  #   else
  #     where{(category_id != nil) & (gender_type.in([GENDER_TYPES[:women], GENDER_TYPES[:both], GENDER_TYPES[:men]]))}    
  #   end
  # end 

  # alias for parent relationship (no gender required, since only one parent exists)
	def parent_category
		category
	end

  # TODO: duplicated from app controller, should be refactored into a helper and then included in this model and in app controller
  def is_numeric?(s)
    !!Float(s) rescue false
  end
  def self.is_numeric?(s)
    !!Float(s) rescue false
  end

  def gender_type
    self.sizes.select("gender_type").group("gender_type").uniq().collect{|s| s.gender_type }
  end

	def relevant_sizes(gender = :women)
    if is_numeric? gender
      cond = {gender_type: gender}
    else
      cond = {gender_type: GENDER_TYPES[gender]}
    end

    # cond = {gender_type: GENDER_TYPES[gender]}
		sizes.empty? ? parent_category.sizes.where(cond) : sizes.where(cond)
	end

  def self.top_levels(gender = :women)
    gender_cond = Category.is_numeric?(gender) ? [GENDER_TYPES[:both], gender] : [GENDER_TYPES[:both], GENDER_TYPES[gender]]
    Category.where(id: Category.with_products(gender_cond).select{categories.category_id}.collect( &:category_id ).uniq ).where{ (category_id == nil) }
  end

  def self.with_products(gender)
    where(id: Category.active_category_ids(gender).uniq )
  end

  def self.active_category_ids(gender)
    User.designers({designer_active: true})
        .joins(products: [items: [:size]])
        .joins(products: :product_categories)
        .where{(products.active == true) & (products.status == my{Product::STATUS[:approved]}) & (items.quantity > 0) & (sizes.gender_type.in( my{ gender } ))}
        .group{product_categories.category_id}
        .select{product_categories.category_id}
        .collect( &:category_id )
  end

  def subcategories_with_product(gender)
    Category.joins{products.items.size}.where{ (sizes.gender_type.in(my{ [gender, GENDER_TYPES[:both]] })) & (items.quantity > 0) & (categories.category_id == my{self.id}) & (products.active == true) & (products.status == my{Product::STATUS[:approved]}) }.uniq
  end


  def self.featured_in_style_directory
    where{ featured_in_style_directory == true }
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
.edit_category
  = form_for(@category) do |f|
    - if @category.errors.any?
      #error_explanation
        h2
          = pluralize(@category.errors.count, "error")
          | prohibited this category from being saved:
        ul
          - @category.errors.full_messages.each do |msg|
            li= msg
    .field
      = f.label :name
      = f.text_field :name
    .cl

    .field
      = label "switch", "Is Subcategory"
      = check_box_tag("switch", "is_subcat", !@category.category_id.blank?, { :class => 'switch' })
    .cl

    .field.category_id(style="display: #{@category.category_id.blank? ? "none" : "block"}")
      = f.label :category_id
      = f.select :category_id, Category.where(category_id: nil).collect{|c| [c.name, c.id] }, { include_blank: true }
    .cl

    .field.banner(style="display: #{@category.category_id.blank? ? "block" : "none"}")
      = f.label :banner
      = f.file_field :banner
    .cl

    .field.featured-in-style-directory(style="display: #{@category.category_id.blank? ? "block" : "none"}")
      = f.label :featured_in_style_directory
      = f.check_box :featured_in_style_directory
    .cl

    .field.featured-in-style-directory(style="display: #{@category.category_id.blank? ? "block" : "none"}")
      = f.label :style_directory_image
      = f.file_field :style_directory_image
    .cl

    .field.size-chart-man
      = f.label :size_chart_man
      = f.file_field :size_chart_man
    .cl

    .field.size-chart-woman
      = f.label :size_chart_woman
      = f.file_field :size_chart_woman
    .cl

    .field.size-chart-unisex
      = f.label :size_chart_unisex
      = f.file_field :size_chart_unisex
    .cl    

    br
    br
    - if @category.banner.exists?
      .featured-in-style-directory
        em Current Banner
        br
        = image_tag @category.banner(:small)

    - if @category.style_directory_image.exists?
      .featured-in-style-directory
        em Current Style Directory Image
        br
        = image_tag @category.style_directory_image(:small)


    - if @category.size_chart_man.exists?
      .featured-in-style-directory
        em Man Size Chart
        br
        = image_tag @category.size_chart_man

    - if @category.size_chart_woman.exists?
      .featured-in-style-directory
        em Woman Size Chart
        br
        = image_tag @category.size_chart_woman

    - if @category.size_chart_unisex.exists?
      .featured-in-style-directory
        em Unisex Size Chart
        br
        = image_tag @category.size_chart_unisex





    .buttons
      = f.submit "Save", class: "button dark"
  .cl

app/views/categories/edit.html.slim
- title @category.name
- meta_description "#{@category.name} description."
- meta_keywords @category.name

h1 Editing category
= render 'form'
= link_to 'Show', @category
br
= link_to 'Back', categories_path

app/views/categories/index.html.slim
- title "Categories"
- meta_description "admin categories description."
- meta_keywords "Category"
h1.dashboard_index Listing categories
.buttons.dashboard_index
  = link_to 'New Category', new_category_path, class: "button dark"
table.dashboard_table
  tr
    th Name
    th Parent
    th Actions

  - @categories.each do |category|
    tr
      td= category.name
      td= category.category ? category.category.name : ''
      td
        = link_to 'Show', category
        ' 
        = link_to 'Edit', edit_category_path(category)
        ' 
        = link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete
.cl

app/views/categories/new.html.slim
h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/categories/show.html.slim
- title @category.name
- meta_description "#{@category.name} description."
- meta_keywords @category.name

- content_for :admin_menu do
  = render partial: "/shared/add_to_home_page",locals: {entity: @category}

- content_for :javascript_includes do
  javascript:
    $(function(){
      INFINITE_SCROLLING.setup(".loading_area");
    })

- if user_signed_in? and current_user.is_admin?
  - content_for :admin_menu do
    li= link_to 'Edit Category', edit_category_path(@category)


- cache "views_category_show_#{@category_ids}_#{session_gender}" do
  .post
    .image
      = image_tag @parent_category.banner.url(:banner)
      h2.mercury-region#country_name data-type="editable" data-mercury="simple"
        = raw @parent_category.name

  == render partial: "/shared/product_filters", locals: {form_url: category_path(@category), categories: @category.subcategories_with_product(session_gender), designers: @designers, countries: @countries}

  .featured
  	== render partial: "/products/products", locals: {products: @products, id: 'products', no_pagination: true}
  .loading_area style="text-align:center"